### ISSUE TITLE
mac 下  代码编辑器无法复制粘贴

### ISSUE THREAD

**Issue by ShaunSong** [Holaverse/HolaStudioLocalEdition#1]
mac 下  代码编辑器无法复制粘贴
另外  预览地址  无法复制  没法在浏览器里面debug
语言时候alert 等js的打印不支持

**Comment by Luncher** [comment]
what ?还没正式发布就用上了？

**Comment by Luncher** [comment]
下个版本修复了以下问题：  
- 代码编辑器无法复制粘贴  
- 需要`debug`可以直接在编辑器页面按下`f12`调式  (windows由于特殊限制，需要按下`f6`进行调式)  
- 在编辑器内部预览alert语句不支持，其他console语句支持、在新窗口预览`alert`以及`console`都支持
